use crate::executor::ssh::SshExecutor;
use crate::models::ManagedServer;
use serde::{Deserialize, Serialize};

/// Basic operating system information collected during discovery.
#[derive(Debug, Serialize, Deserialize)]
pub struct SystemInfo {
    /// The pretty name of the OS (e.g., "Ubuntu 22.04 LTS").
    pub os_release: String,
    /// The kernel version.
    pub kernel_version: String,
    /// The server's hostname.
    pub hostname: String,
    /// The system uptime.
    pub uptime: String,
}

/// Resource usage statistics.
#[derive(Debug, Serialize, Deserialize)]
pub struct Resources {
    /// CPU Load Average (1, 5, 15 min).
    pub cpu_usage: String,
    /// Memory usage (Used / Total).
    pub memory_usage: String,
    /// Disk usage for root partition (Used / Total (Percentage)).
    pub disk_usage: String,
}

/// Information about a running system service.
#[derive(Debug, Serialize, Deserialize)]
pub struct RunningService {
    /// The name of the service unit (e.g., "ssh.service").
    pub name: String,
    /// The status of the service (usually "running").
    pub status: String,
}

/// A comprehensive report of the server's status generated by the discovery process.
#[derive(Debug, Serialize, Deserialize)]
pub struct DiscoveryReport {
    pub system_info: SystemInfo,
    pub resources: Resources,
    pub services: Vec<RunningService>,
    pub timestamp: String,
}

/// A module for discovering and gathering information about a remote server.
pub struct Discovery;

impl Discovery {
    /// Connects to the specified server and gathers system information.
    ///
    /// This method runs a series of SSH commands to collect:
    /// - OS details (`/etc/os-release`, `uname`)
    /// - Resource usage (`uptime`, `free`, `df`)
    /// - Running services (`systemctl`)
    ///
    /// # Arguments
    ///
    /// * `server` - The target server to discover.
    ///
    /// # Returns
    ///
    /// A `DiscoveryReport` containing all gathered data, or an error if connection fails.
    pub fn run(server: &ManagedServer) -> Result<DiscoveryReport, String> {
        // Gather System Info
        let os_release = SshExecutor::execute(
            server,
            "cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '\"'",
        )
        .unwrap_or_else(|_| "Unknown".to_string());

        let kernel =
            SshExecutor::execute(server, "uname -r").unwrap_or_else(|_| "Unknown".to_string());

        let hostname =
            SshExecutor::execute(server, "hostname").unwrap_or_else(|_| "Unknown".to_string());

        let uptime =
            SshExecutor::execute(server, "uptime -p").unwrap_or_else(|_| "Unknown".to_string());

        let system_info = SystemInfo {
            os_release: os_release.trim().to_string(),
            kernel_version: kernel.trim().to_string(),
            hostname: hostname.trim().to_string(),
            uptime: uptime.trim().to_string(),
        };

        // Gather Resources
        let load_avg = SshExecutor::execute(server, "cat /proc/loadavg | awk '{print $1, $2, $3}'")
            .unwrap_or_else(|_| "Unknown".to_string());

        let memory =
            SshExecutor::execute(server, "free -h | grep Mem | awk '{print $3 \" / \" $2}'")
                .unwrap_or_else(|_| "Unknown".to_string());

        let disk = SshExecutor::execute(
            server,
            "df -h / | tail -n 1 | awk '{print $3 \" / \" $2 \" (\" $5 \")\"}'",
        )
        .unwrap_or_else(|_| "Unknown".to_string());

        let resources = Resources {
            cpu_usage: format!("Load Avg: {}", load_avg.trim()),
            memory_usage: memory.trim().to_string(),
            disk_usage: disk.trim().to_string(),
        };

        // Gather Services (Top 10 running)
        // using systemctl list-units --type=service --state=running
        let services_raw = SshExecutor::execute(server, "systemctl list-units --type=service --state=running --no-pager --plain | head -n 15 | awk '{print $1}'")
             .unwrap_or_else(|_|"".to_string());

        let services: Vec<RunningService> = services_raw
            .lines()
            .filter(|line| line.contains(".service"))
            .map(|line| RunningService {
                name: line.trim().to_string(),
                status: "running".to_string(),
            })
            .collect();

        Ok(DiscoveryReport {
            system_info,
            resources,
            services,
            timestamp: chrono::Local::now().to_string(),
        })
    }
}
