use serde::{Deserialize, Serialize};

/// Represents a server managed by the PocketSentinel agent.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ManagedServer {
    /// Unique identifier for the server.
    pub id: String,
    /// The hostname or alias.
    pub hostname: String,
    /// The IP address for connection.
    pub ip_address: String,
    /// The SSH port (usually 22).
    pub port: u16,
    /// The user to authenticate as.
    pub ssh_user: String,
    /// Optional password (keys are preferred).
    pub password: Option<String>,
}

/// Defines the status of a specific task within the agent's workflow.
///
/// *Note: This enum is currently unused but reserved for future task management features.*
#[derive(Debug, Serialize, Deserialize, Clone)]
#[allow(dead_code)]
pub enum TaskStatus {
    Pending,
    Executing,
    Completed,
    Failed(String),
}

/// The core instruction generated by the AI reasoning layer.
///
/// *Note: This struct is currently unused but reserved for future autonomous agent features.*
#[derive(Debug, Serialize, Deserialize, Clone)]
#[allow(dead_code)]
pub struct AgentTask {
    pub task_id: String,
    pub server_id: String,
    pub command: String,
    pub description: String,
    pub status: TaskStatus,
}

pub mod command;

#[derive(Debug, Clone)]
pub enum CommandResponse {
    Text(String),
    Html(String),
    InteractiveList {
        title: String,
        options: Vec<String>,
        callback_prefix: String,
    },
}
