use serde::{Deserialize, Serialize};

// Represents a server managed by the agent
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ManagedServer {
    pub id: String,
    pub hostname: String,
    pub ip_address: String,
    pub ssh_user: String,
}

// Defines the status of a specific task
#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum TaskStatus {
    Pending,
    Executing,
    Completed,
    Failed(String),
}

// The core instruction generated by the AI reasoning layer
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AgentTask {
    pub task_id: String,
    pub server_id: String,
    pub command: String,
    pub description: String,
    pub status: TaskStatus,
}
