// src/main.rs

// Module declarations
mod ai;
mod core;
mod executor;
mod models;

use models::{AgentTask, ManagedServer, TaskStatus};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Load environment variables from .env file
    dotenv::dotenv().ok();

    println!("PocketSentinel Agent Initializing...");

    // 1. Mock: Define a target server
    let target_server = ManagedServer {
        id: String::from("prod-01"),
        hostname: String::from("production-api"),
        ip_address: String::from("192.168.1.50"),
        ssh_user: String::from("deploy"),
    };

    // 2. Mock: Simulate a task generated by the AI logic
    let mut current_task = AgentTask {
        task_id: String::from("task-101"),
        server_id: target_server.id.clone(),
        command: String::from("docker-compose up -d"),
        description: String::from("Deploying latest changes via mobile request"),
        status: TaskStatus::Pending,
    };

    println!(
        "Processing Task: {} on Server: {}",
        current_task.description, target_server.hostname
    );

    // 3. Execution logic (To be implemented in the executor module)
    // For now, we just simulate success
    current_task.status = TaskStatus::Completed;

    println!("Task Status: {:?}", current_task.status);

    Ok(())
}
